blank_issues_enabled: false
contact_links:
  - name: Mod Discord
    url: https://discord.gg/wuamm4P
    about: If you are not sure about something, ask on Discord
  - name: Vampirism repository
    url: https://github.com/TeamLapen/Vampirism
    about: Report mod incompatibilities (like crashes or exploits) on the main repository